import type { Metadata } from "next";
import "../styles/globals.css";
import { geistMono, inter, satoshi } from "../styles/font";
import { Providers } from "../components/provider";
import { Appbar } from "../components/Appbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable}, ${satoshi.variable}, ${geistMono.variable}`}
    >
      <body>
        <Providers>
          <Appbar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
