import type { Metadata } from "next";
import "../styles/globals.css";
import { geistMono, inter, satoshi } from "../styles/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable}, ${satoshi.variable}, ${geistMono.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
